### ISSUE TITLE
USB Not working after updating to 11.3.1

### ISSUE THREAD

**Issue by Nking217** [SiddheshNan/Acer-A515-51G-Hackintosh-OpenCore#10]
My USB 3 ports (USB A and USB Type C) is not working after updating to mac os 11.3.1. I tried to fix the USBinjectall kext and it's still not working. pls help

**Comment by leandrofgodoy** [comment]
Disable the XhciPortLimit save me from this issue.

**Comment by Nking217** [comment]
It's working Thx

**Comment by luizgallas** [comment]
How can I disable it?

**Comment by leandrofgodoy** [comment]
Into OpenCore Config.

**Comment by luizgallas** [comment]
Doesnt work for me, hault error on boot
