### ISSUE TITLE
USB 3.0 and USB-C ports from the left side aren't recognized after updating from Big Sur 11.2.5 to 11.6.5

### ISSUE THREAD

**Issue by euaaron** [SiddheshNan/Acer-A515-51G-Hackintosh-OpenCore#15]
The title says everything.

All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.

They are still working on Windows or during OpenCore Boot screen, but not from MacOS...

I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.

> My notebook is an Acer A515-51G-50W8.

Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext? 
Or know what I could do to make them work again?

**Comment by ghost** [comment]
> The title says everything.
> 
> All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.
> 
> They are still working on Windows or during OpenCore Boot screen, but not from MacOS...
> 
> I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.
> 
> > My notebook is an Acer A515-51G-50W8.
> 
> Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext? Or know what I could do to make them work again?

https://github.com/amaterasushen/opencore-efi--a515-51G--monterey-ventura

**Comment by euaaron** [comment]
> The title says everything.
> 
> All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.
> 
> They are still working on Windows or during OpenCore Boot screen, but not from MacOS...
> 
> I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.
> 
> > My notebook is an Acer A515-51G-50W8.
> 
> Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext? 
> Or know what I could do to make them work again?

Fixed it!

I was using USBMap wrongly, the right is mapping through Windows not from macOS :)

Before version 11.6.5 they just worked well with USBInjectAll.

I'm now using macOS Ventura beta 2, upgraded from Monterey and never needed to map again after doing it on Windows.

**Comment by ghost** [comment]
> > The title says everything.
> > All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.
> > They are still working on Windows or during OpenCore Boot screen, but not from MacOS...
> > I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.
> > > My notebook is an Acer A515-51G-50W8.
> > 
> > 
> > Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext?
> > Or know what I could do to make them work again?
> 
> Fixed it!
> 
> I was using USBMap wrongly, the right is mapping through Windows not from macOS :)
> 
> Before version 11.6.5 they just worked well with USBInjectAll.
> 
> I'm now using macOS Ventura beta 2, upgraded from Monterey and never needed to map again after doing it on Windows.

can you share your USBmap with me? (I got it from a different acer model) mine only works on monterey, I can't use it on the ventura beta. Which SMBIOS are you using?

**Comment by euaaron** [comment]
> > > The title says everything.
> > > All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.
> > > They are still working on Windows or during OpenCore Boot screen, but not from MacOS...
> > > I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.
> > > > My notebook is an Acer A515-51G-50W8.
> > > 
> > > 
> > > Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext?
> > > Or know what I could do to make them work again?
> > 
> > 
> > Fixed it!
> > I was using USBMap wrongly, the right is mapping through Windows not from macOS :)
> > Before version 11.6.5 they just worked well with USBInjectAll.
> > I'm now using macOS Ventura beta 2, upgraded from Monterey and never needed to map again after doing it on Windows.
> 
> can you share your USBmap with me? (I got it from a different acer model) mine only works on monterey, I can't use it on the ventura beta. Which SMBIOS are you using?

Sure! I will upload my EFI here and update this comment with a link to it.

Also, if you don't use yet, I recommend you to use [OCAuxiliaryTools](https://github.com/ic005k/OCAuxiliaryTools) it helps a to upgrade opencore and everything inside it.

Another point is that I'm using Ventura Beta 2, I still couldn't upgrade to Beta 3... still need to figure out what I need to change.

**Comment by ghost** [comment]
> > > > The title says everything.
> > > > All USB ports where working well but after updating to Big Sur 11.6.5 the USB ports from the left side just stopped.
> > > > They are still working on Windows or during OpenCore Boot screen, but not from MacOS...
> > > > I've already tried to map them using [USBMap](https://github.com/corpnewt/USBMap) but did't worked.
> > > > > My notebook is an Acer A515-51G-50W8.
> > > > 
> > > > 
> > > > Does anyone have this notebook and is using **Monterey** or **Big Sur 11.6.5** with a working USB kext?
> > > > Or know what I could do to make them work again?
> > > 
> > > 
> > > Fixed it!
> > > I was using USBMap wrongly, the right is mapping through Windows not from macOS :)
> > > Before version 11.6.5 they just worked well with USBInjectAll.
> > > I'm now using macOS Ventura beta 2, upgraded from Monterey and never needed to map again after doing it on Windows.
> > 
> > 
> > can you share your USBmap with me? (I got it from a different acer model) mine only works on monterey, I can't use it on the ventura beta. Which SMBIOS are you using?
> 
> Sure! I will upload my EFI here and update this comment with a link to it.
> 
> Also, if you don't use yet, I recommend you to use [OCAuxiliaryTools](https://github.com/ic005k/OCAuxiliaryTools) it helps a to upgrade opencore and everything inside it.
> 
> Another point is that I'm using Ventura Beta 2, I still couldn't upgrade to Beta 3... still need to figure out what I need to change.

my opencore is 100%, but I really couldn't get USB to work, nor does USBinjectall work for me. Anyway, how is your hackintosh performing? mine is not very good, it scores 500 ~ 800 points in geekebench singlecore, and on Linux and Windows I get about 940+. I already tried to change a lot of things and it still seems slow, is there anything that can help me find the problem?, I made my EFI 100 from scratch, I just reused another guy's USBmap.

**Comment by euaaron** [comment]
@amaterasushen here is my [updated fork of this repo](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore). You may want to check for everything with USB on the name inside /kext folder. ([USBToolBox.kext](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore/tree/main/EFI/OC/Kexts/USBToolBox.kext) and [UTBMap.kext](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore/tree/main/EFI/OC/Kexts/UTBMap.kext))

About the benchmark, I haven't done it yet... but I never had any problem on macOS as I did on Windows, like lags, sudden reboots or anything. The battery is even lasting longer (probably because I'm not using the e-gpu on macOS... yet).

**Comment by ghost** [comment]
> @amaterasushen here is my [updated fork of this repo](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore). You may want to check for everything with USB on the name inside /kext folder.
> 
> About the benchmark, I haven't done it yet... but I never had any problem on macOS as I did on Windows, like lags, sudden reboots or anything. The battery is even lasting longer (probably because I'm not using the e-gpu on macOS... yet).

Are you using MacbookPro14.2 smbios?

**Comment by euaaron** [comment]
> > @amaterasushen here is my [updated fork of this repo](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore). You may want to check for everything with USB on the name inside /kext folder.
> > About the benchmark, I haven't done it yet... but I never had any problem on macOS as I did on Windows, like lags, sudden reboots or anything. The battery is even lasting longer (probably because I'm not using the e-gpu on macOS... yet).
> 
> Are you using MacbookPro14.2 smbios?

Yes! I was using 15,2 before Ventura and also SkyLake config, just like as this repo tell us to use and it was working fine. But then I had troubles updating to Ventura and I decided to switch to my laptop original config, that is a KabyLake and a i5-7200U. Ventura dropped support for SkyLake.

> If you decide to change, remember to log out your AppleID from the system and from Messages app.

**Comment by euaaron** [comment]
> > > @amaterasushen here is my [updated fork of this repo](https://github.com/euaaron/Acer-A515-51G-Hackintosh-OpenCore). You may want to check for everything with USB on the name inside /kext folder.
> > > About the benchmark, I haven't done it yet... but I never had any problem on macOS as I did on Windows, like lags, sudden reboots or anything. The battery is even lasting longer (probably because I'm not using the e-gpu on macOS... yet).
> > 
> > 
> > Are you using MacbookPro14.2 smbios?
> 
> Yes! I was using 15,2 before Ventura and also SkyLake config, just like as this repo tell us to use and it was working fine. But then I had troubles updating to Ventura and I decided to switch to my laptop original config, that is a KabyLake and a i5-7200U. Ventura dropped support for SkyLake.

If you decide to change, remember to log out your AppleID from the system and from Messages app.

**Comment by euaaron** [comment]
BTW about the benchmark, here's [how it is on macOS](https://browser.geekbench.com/v5/cpu/15981360) and [this is the result from Windows](https://browser.geekbench.com/v5/cpu/15981202). The average for my processor is 450 points, I'm surprised that macOS and Windows got 500+.
